### ISSUE TITLE
Doesn't work on Amazon Linux with gedit 3.28.1

### ISSUE THREAD

**Issue by Gianluca755** [lwindolf/gedit-pluginbrowser#10]
It doesn't work and causes a reset of the gedit configuration.

**Comment by lwindolf** [comment]
Can you give more details regarding the configuration reset?

**Comment by Gianluca755** [comment]
I install the plugin with the instructions on GitHub. Plugin installer is present in the plugin list in gedit.
If I select it I got `plugin loader 'python3' was not found`, found [this](https://stackoverflow.com/questions/28964474/gedit-plugin-error-plugin-loader-python3-was-not-found) with setting `Loader=python` but no result, tried 2to3 on the code but it failed with:
```
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No changes to appactivatable.py
Traceback (most recent call last):
  File "/bin/2to3", line 5, in <module>
    sys.exit(main("lib2to3.fixes"))
  File "/usr/lib64/python3.7/lib2to3/main.py", line 259, in main
    options.processes)
  File "/usr/lib64/python3.7/lib2to3/refactor.py", line 687, in refactor
    items, write, doctests_only)
  File "/usr/lib64/python3.7/lib2to3/refactor.py", line 282, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/usr/lib64/python3.7/lib2to3/refactor.py", line 728, in refactor_file
    *args, **kwargs)
  File "/usr/lib64/python3.7/lib2to3/refactor.py", line 322, in refactor_file
    input, encoding = self._read_python_source(filename)
  File "/usr/lib64/python3.7/lib2to3/refactor.py", line 318, in _read_python_source
    return f.read(), encoding
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
```

It is probably my fault due to some config.

**Comment by lwindolf** [comment]
I think switching the loader won't help. Sadly I cannot help with how to install necessary dependencies on Amazon Linux.
