### ISSUE TITLE
Cannot install plugins or access the plugin's settings

### ISSUE THREAD

**Issue by leoniscsem** [lwindolf/gedit-pluginbrowser#9]
Ubuntu 20.04
gedit 3.36.2

When pressing the **install plugins** button:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/appactivatable.py", line 51, in _run
    self._get_browser().show_all()
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/appactivatable.py", line 48, in _get_browser
    return PluginBrowser()
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/pluginbrowser.py", line 53, in __init__
    self._plugin_list = self.fetch_list()
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/pluginbrowser.py", line 127, in fetch_list
    resp = urllib.request.urlopen(req).read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt>
```

When trying to access the plugin's settings:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/appactivatable.py", line 45, in do_create_configure_widget
    return self._get_browser()
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/appactivatable.py", line 48, in _get_browser
    return PluginBrowser()
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/pluginbrowser.py", line 53, in __init__
    self._plugin_list = self.fetch_list()
  File "/home/USER/.local/share/gedit/plugins/plugininstaller/pluginbrowser.py", line 127, in fetch_list
    resp = urllib.request.urlopen(req).read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt>

(gedit:774918): libpeas-gtk-CRITICAL **: 17:50:34.606: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed

(gedit:774918): Gtk-CRITICAL **: 17:50:45.494: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gedit:774918): Gtk-CRITICAL **: 17:50:45.497: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gedit:774918): Gtk-CRITICAL **: 17:50:45.500: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gedit:774918): Gtk-CRITICAL **: 17:50:45.504: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

```

**Comment by lwindolf** [comment]
Hmm.. the URLError looks very much like a network error. Are you maybe using a proxy?

Also the plugin does not work when used in a sandbox (e.g. flatpack). Please ensure to use a native Gedit package.

**Comment by leoniscsem** [comment]
I am using the native package that comes with Ubuntu 20.04. No proxy involved, but I am located in China, so perhaps the Great Firewall (yet again... #§$%!) might play a role here.

**Comment by lwindolf** [comment]
Yep, sounds like the Great Firewall (https://www.techinasia.com/github-blocked-china). The plugin is list as well as the plugins are fetched via github... 

Sorry you need to manually download plugins!
